import { Post, User } from "@/src/interfaces";

export const mockUsers: User[] = [
  {
    id: "1",
    name: "Juan Pérez",
    email: "juan@example.com",
    image: "https://api.dicebear.com/7.x/avataaars/svg?seed=Juan",
  },
  {
    id: "2",
    name: "María García",
    email: "maria@example.com",
    image: "https://api.dicebear.com/7.x/avataaars/svg?seed=Maria",
  },
  {
    id: "3",
    name: "Carlos López",
    email: "carlos@example.com",
    image: "https://api.dicebear.com/7.x/avataaars/svg?seed=Carlos",
  },
  {
    id: "4",
    name: "Ana Martínez",
    email: "ana@example.com",
    image: "https://api.dicebear.com/7.x/avataaars/svg?seed=Ana",
  },
];

export const mockPosts: Post[] = [
  {
    id: "1",
    userId: "2",
    userName: "María García",
    userImage: "https://api.dicebear.com/7.x/avataaars/svg?seed=Maria",
    content: "¡Qué hermoso día para compartir momentos especiales! 🌞✨",
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    likes: 12,
    likedBy: ["1", "3"],
    shares: 3,
    isFavorite: false,
    favoritedBy: [],
    comments: [
      {
        id: "1",
        postId: "1",
        userId: "1",
        userName: "Juan Pérez",
        userImage: "https://api.dicebear.com/7.x/avataaars/svg?seed=Juan",
        content: "¡Totalmente de acuerdo! 😊",
        createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
        likes: 5,
        likedBy: ["2"],
      },
      {
        id: "2",
        postId: "1",
        userId: "3",
        userName: "Carlos López",
        userImage: "https://api.dicebear.com/7.x/avataaars/svg?seed=Carlos",
        content: "Hermoso día, sin duda.",
        createdAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
        likes: 2,
        likedBy: [],
      },
    ],
  },
  {
    id: "2",
    userId: "3",
    userName: "Carlos López",
    userImage: "https://api.dicebear.com/7.x/avataaars/svg?seed=Carlos",
    content:
      'Acabo de terminar de leer un libro increíble. ¿Alguien más ha leído "El Programador Pragmático"? 📚',
    imageUrl:
      "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=800&h=600&fit=crop",
    createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    likes: 28,
    likedBy: ["1", "2", "4"],
    shares: 7,
    isFavorite: true,
    favoritedBy: ["1"],
    comments: [
      {
        id: "3",
        postId: "2",
        userId: "4",
        userName: "Ana Martínez",
        userImage: "https://api.dicebear.com/7.x/avataaars/svg?seed=Ana",
        content: "¡Sí! Es uno de mis favoritos. Muy recomendado.",
        createdAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
        likes: 8,
        likedBy: ["1", "3"],
      },
    ],
  },
  {
    id: "3",
    userId: "4",
    userName: "Ana Martínez",
    userImage: "https://api.dicebear.com/7.x/avataaars/svg?seed=Ana",
    content:
      "Compartiendo algunas fotos de mi viaje a la montaña. ¡La naturaleza es increíble! 🏔️",
    imageUrl:
      "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop",
    createdAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    likes: 45,
    likedBy: ["1", "2", "3"],
    shares: 12,
    isFavorite: false,
    favoritedBy: [],
    comments: [],
  },
  {
    id: "4",
    userId: "1",
    userName: "Juan Pérez",
    userImage: "https://api.dicebear.com/7.x/avataaars/svg?seed=Juan",
    content:
      "¿Alguien más está emocionado por el nuevo framework de React? Las nuevas features son increíbles! 🚀",
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    likes: 67,
    likedBy: ["2", "3", "4"],
    shares: 15,
    isFavorite: true,
    favoritedBy: ["2", "3"],
    comments: [
      {
        id: "4",
        postId: "4",
        userId: "2",
        userName: "María García",
        userImage: "https://api.dicebear.com/7.x/avataaars/svg?seed=Maria",
        content: "¡Sí! Estoy esperando probarlo este fin de semana.",
        createdAt: new Date(Date.now() - 23 * 60 * 60 * 1000).toISOString(),
        likes: 12,
        likedBy: ["1", "3"],
      },
      {
        id: "5",
        postId: "4",
        userId: "3",
        userName: "Carlos López",
        userImage: "https://api.dicebear.com/7.x/avataaars/svg?seed=Carlos",
        content: "He visto las demos, se ve prometedor.",
        createdAt: new Date(Date.now() - 22 * 60 * 60 * 1000).toISOString(),
        likes: 6,
        likedBy: ["1"],
      },
    ],
  },
];
